# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi_main(self, main_page):
        main_page.setObjectName("main_page")
        main_page.setFixedSize(800, 660)


        self.centralwidget = QtWidgets.QWidget(main_page)
        self.centralwidget.setObjectName("centralwidget")

        self.list = QtWidgets.QListWidget(self.centralwidget)
        self.list.setGeometry(QtCore.QRect(0, 340, 800, 210))
        self.list.setObjectName("list")
        self.list_label = QtWidgets.QLabel(self.centralwidget)
        self.list_label.setGeometry(QtCore.QRect(10, 316, 101, 18))
        self.list_label.setObjectName("list_label")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.info_label.setObjectName("info_label")
        self.source_line = QtWidgets.QLineEdit(self.centralwidget)
        self.source_line.setGeometry(QtCore.QRect(110, 210, 540, 32))
        self.source_line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.source_line.setObjectName("source_line")
        self.source_btn = QtWidgets.QPushButton(self.centralwidget)
        self.source_btn.setGeometry(QtCore.QRect(670, 209, 80, 34))
        self.source_btn.setObjectName("source_btn")
        self.source_label = QtWidgets.QLabel(self.centralwidget)
        self.source_label.setGeometry(QtCore.QRect(10, 216, 91, 18))
        self.source_label.setObjectName("source_label")
        self.mode_label = QtWidgets.QLabel(self.centralwidget)
        self.mode_label.setGeometry(QtCore.QRect(10, 65, 100, 20))
        self.mode_label.setObjectName("mode_label")
        self.combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.combo_box.setGeometry(QtCore.QRect(110, 60, 80, 30))
        self.combo_box.setObjectName("combo_box")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        # self.port_label = QtWidgets.QLabel(self.centralwidget)
        # self.port_label.setGeometry(QtCore.QRect(260, 65, 70, 20))
        # self.port_label.setObjectName("port_label")
        # self.port_line = QtWidgets.QLineEdit(self.centralwidget)
        # self.port_line.setGeometry(QtCore.QRect(330, 60, 100, 30))
        # self.port_line.setObjectName("port_line")
        self.restart_small_btn = QtWidgets.QPushButton(self.centralwidget)
        self.restart_small_btn.setGeometry(QtCore.QRect(700, 60, 80, 30))
        self.restart_small_btn.setObjectName("restart_small_btn")
        self.upload_btn = QtWidgets.QPushButton(self.centralwidget)
        self.upload_btn.setGeometry(QtCore.QRect(700, 160, 80, 34))
        self.upload_btn.setObjectName("upload_btn")
        # self.download_btn = QtWidgets.QPushButton(self.centralwidget)
        # self.download_btn.setGeometry(QtCore.QRect(680, 560, 85, 35))
        # self.download_btn.setObjectName("download_btn")
        self.new_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_btn.setGeometry(QtCore.QRect(10, 560, 85, 35))
        self.new_btn.setObjectName("new_btn")
        self.previous_btn = QtWidgets.QPushButton(self.centralwidget)
        self.previous_btn.setGeometry(QtCore.QRect(110, 560, 85, 35))
        self.previous_btn.setObjectName("previous_btn")
        self.upload_label = QtWidgets.QLabel(self.centralwidget)
        self.upload_label.setGeometry(QtCore.QRect(30, 116, 58, 18))
        self.upload_label.setObjectName("upload_label")
        self.upload_line = QtWidgets.QLineEdit(self.centralwidget)
        self.upload_line.setGeometry(QtCore.QRect(110, 110, 670, 30))
        self.upload_line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.upload_line.setObjectName("upload_line")
        self.scan_btn = QtWidgets.QPushButton(self.centralwidget)
        self.scan_btn.setGeometry(QtCore.QRect(600, 160, 80, 34))
        self.scan_btn.setObjectName("scan_btn")
        self.scan_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.scan_btn_2.setGeometry(QtCore.QRect(670, 259, 80, 34))
        self.scan_btn_2.setObjectName("scan_btn_2")
        self.info_line = QtWidgets.QLineEdit(self.centralwidget)
        self.info_line.setGeometry(QtCore.QRect(110, 20, 670, 30))
        self.info_line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.info_line.setObjectName("info_line")
        self.target_line = QtWidgets.QLineEdit(self.centralwidget)
        self.target_line.setGeometry(QtCore.QRect(110, 260, 540, 32))
        self.target_line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.target_line.setObjectName("target_line")
        self.target_label = QtWidgets.QLabel(self.centralwidget)
        self.target_label.setGeometry(QtCore.QRect(10, 266, 91, 18))
        self.target_label.setObjectName("target_label")
        main_page.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_page)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        main_page.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_page)
        self.statusbar.setObjectName("statusbar")
        main_page.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(main_page)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(main_page)
        QtCore.QMetaObject.connectSlotsByName(main_page)

    def retranslateUi(self, main_page):
        _translate = QtCore.QCoreApplication.translate
        main_page.setWindowTitle(_translate("main_page", "FTP Client by tuyc17"))
        self.list_label.setText(_translate("main_page", "服务端文件列表"))
        self.info_label.setText(_translate("main_page", "服务器返回信息"))
        self.source_label.setText(_translate("main_page", "服务端当前目录"))
        self.mode_label.setText(_translate("main_page", "文件传输方式"))
        self.combo_box.setItemText(0, _translate("main_page", "Passive"))
        self.combo_box.setItemText(1, _translate("main_page", "Port"))
        # self.port_label.setText(_translate("main_page", "端口号"))
        self.source_btn.setText(_translate("main_page", "刷新"))
        self.restart_small_btn.setText(_translate("main_page", "断点续传"))
        self.upload_btn.setText(_translate("main_page", "上传"))
        # self.download_btn.setText(_translate("main_page", "下载"))
        self.new_btn.setText(_translate("main_page", "新建文件夹"))
        self.previous_btn.setText(_translate("main_page", "返回上级目录"))
        self.upload_label.setText(_translate("main_page", "文件上传"))
        self.scan_btn.setText(_translate("main_page", "浏览..."))
        self.scan_btn_2.setText(_translate("main_page", "浏览..."))
        self.target_label.setText(_translate("main_page", "客户端目标路径"))
        self.menu.setTitle(_translate("main_page", "Help"))
        self.actionAbout.setText(_translate("main_page", "About..."))
